ln -s ../../../../../src/systemc/Tlm.py ./
ln -s ../../../../../src/systemc/core/SystemC.py ./
ln -s ../../../../../src/systemc/tlm_bridge/TlmBridge.py ./
ln -s ../../../../../src/arch/x86/X86SeWorkload.py ./
ln -s ../../../../../src/arch/x86/X86FsWorkload.py ./
ln -s ../../../../../src/arch/x86/X86Decoder.py ./
ln -s ../../../../../src/arch/x86/X86ISA.py ./
ln -s ../../../../../src/arch/x86/X86LocalApic.py ./
ln -s ../../../../../src/arch/x86/X86MMU.py ./
ln -s ../../../../../src/arch/x86/X86NativeTrace.py ./
ln -s ../../../../../src/arch/x86/X86TLB.py ./
ln -s ../../../../../src/arch/x86/X86CPU.py ./
ln -s ../../../../../src/arch/x86/bios/E820.py ./
ln -s ../../../../../src/arch/x86/bios/SMBios.py ./
ln -s ../../../../../src/arch/x86/bios/IntelMP.py ./
ln -s ../../../../../src/arch/x86/bios/ACPI.py ./
ln -s ../../../../../src/arch/x86/kvm/X86KvmCPU.py ./
ln -s ../../../../../src/arch/generic/BaseInterrupts.py ./
ln -s ../../../../../src/arch/generic/BaseISA.py ./
ln -s ../../../../../src/arch/generic/BaseMMU.py ./
ln -s ../../../../../src/arch/generic/BaseTLB.py ./
ln -s ../../../../../src/arch/generic/InstDecoder.py ./
ln -s ../../../../../src/sim/ClockedObject.py ./
ln -s ../../../../../src/sim/TickedObject.py ./
ln -s ../../../../../src/sim/Workload.py ./
ln -s ../../../../../src/sim/Root.py ./
ln -s ../../../../../src/sim/ClockDomain.py ./
ln -s ../../../../../src/sim/VoltageDomain.py ./
ln -s ../../../../../src/sim/System.py ./
ln -s ../../../../../src/sim/DVFSHandler.py ./
ln -s ../../../../../src/sim/SubSystem.py ./
ln -s ../../../../../src/sim/RedirectPath.py ./
ln -s ../../../../../src/sim/PowerState.py ./
ln -s ../../../../../src/sim/PowerDomain.py ./
ln -s ../../../../../src/sim/SignalPort.py ./
ln -s ../../../../../src/sim/InstTracer.py ./
ln -s ../../../../../src/sim/Process.py ./
ln -s ../../../../../src/sim/power/MathExprPowerModel.py ./
ln -s ../../../../../src/sim/power/PowerModel.py ./
ln -s ../../../../../src/sim/power/PowerModelState.py ./
ln -s ../../../../../src/sim/power/ThermalDomain.py ./
ln -s ../../../../../src/sim/power/ThermalModel.py ./
ln -s ../../../../../src/sim/probe/Probe.py ./
ln -s ../../../../../src/cpu/FuncUnit.py ./
ln -s ../../../../../src/cpu/StaticInstFlags.py ./
ln -s ../../../../../src/cpu/InstPBTrace.py ./
ln -s ../../../../../src/cpu/CheckerCPU.py ./
ln -s ../../../../../src/cpu/BaseCPU.py ./
ln -s ../../../../../src/cpu/CpuCluster.py ./
ln -s ../../../../../src/cpu/CPUTracers.py ./
ln -s ../../../../../src/cpu/TimingExpr.py ./
ln -s ../../../../../src/cpu/DummyChecker.py ./
ln -s ../../../../../src/cpu/minor/BaseMinorCPU.py ./
ln -s ../../../../../src/cpu/minor/MinorCPU.py ./
ln -s ../../../../../src/cpu/probes/PcCountTracker.py ./
ln -s ../../../../../src/cpu/testers/garnet_synthetic_traffic/GarnetSyntheticTraffic.py ./
ln -s ../../../../../src/cpu/testers/traffic_gen/BaseTrafficGen.py ./
ln -s ../../../../../src/cpu/testers/traffic_gen/GUPSGen.py ./
ln -s ../../../../../src/cpu/testers/traffic_gen/PyTrafficGen.py ./
ln -s ../../../../../src/cpu/testers/traffic_gen/TrafficGen.py ./
ln -s ../../../../../src/cpu/testers/memtest/MemTest.py ./
ln -s ../../../../../src/cpu/testers/rubytest/RubyTester.py ./
ln -s ../../../../../src/cpu/testers/directedtest/RubyDirectedTester.py ./
ln -s ../../../../../src/cpu/kvm/KvmVM.py ./
ln -s ../../../../../src/cpu/kvm/BaseKvmCPU.py ./
ln -s ../../../../../src/cpu/pred/BranchPredictor.py ./
ln -s ../../../../../src/cpu/o3/FUPool.py ./
ln -s ../../../../../src/cpu/o3/FuncUnitConfig.py ./
ln -s ../../../../../src/cpu/o3/BaseO3CPU.py ./
ln -s ../../../../../src/cpu/o3/BaseO3Checker.py ./
ln -s ../../../../../src/cpu/o3/O3CPU.py ./
ln -s ../../../../../src/cpu/o3/O3Checker.py ./
ln -s ../../../../../src/cpu/o3/probe/SimpleTrace.py ./
ln -s ../../../../../src/cpu/o3/probe/ElasticTrace.py ./
ln -s ../../../../../src/cpu/simple/BaseAtomicSimpleCPU.py ./
ln -s ../../../../../src/cpu/simple/BaseNonCachingSimpleCPU.py ./
ln -s ../../../../../src/cpu/simple/BaseTimingSimpleCPU.py ./
ln -s ../../../../../src/cpu/simple/BaseSimpleCPU.py ./
ln -s ../../../../../src/cpu/simple/AtomicSimpleCPU.py ./
ln -s ../../../../../src/cpu/simple/NonCachingSimpleCPU.py ./
ln -s ../../../../../src/cpu/simple/TimingSimpleCPU.py ./
ln -s ../../../../../src/cpu/simple/probes/SimPoint.py ./
ln -s ../../../../../src/cpu/trace/TraceCPU.py ./
ln -s ../../../../../src/mem/CommMonitor.py ./
ln -s ../../../../../src/mem/AbstractMemory.py ./
ln -s ../../../../../src/mem/AddrMapper.py ./
ln -s ../../../../../src/mem/Bridge.py ./
ln -s ../../../../../src/mem/SysBridge.py ./
ln -s ../../../../../src/mem/MemCtrl.py ./
ln -s ../../../../../src/mem/HeteroMemCtrl.py ./
ln -s ../../../../../src/mem/HBMCtrl.py ./
ln -s ../../../../../src/mem/MemInterface.py ./
ln -s ../../../../../src/mem/DRAMInterface.py ./
ln -s ../../../../../src/mem/NVMInterface.py ./
ln -s ../../../../../src/mem/ExternalMaster.py ./
ln -s ../../../../../src/mem/ExternalSlave.py ./
ln -s ../../../../../src/mem/CfiMemory.py ./
ln -s ../../../../../src/mem/SharedMemoryServer.py ./
ln -s ../../../../../src/mem/SimpleMemory.py ./
ln -s ../../../../../src/mem/XBar.py ./
ln -s ../../../../../src/mem/HMCController.py ./
ln -s ../../../../../src/mem/SerialLink.py ./
ln -s ../../../../../src/mem/MemDelay.py ./
ln -s ../../../../../src/mem/PortTerminator.py ./
ln -s ../../../../../src/mem/ThreadBridge.py ./
ln -s ../../../../../src/mem/MemChecker.py ./
ln -s ../../../../../src/mem/ruby/slicc_interface/Controller.py ./
ln -s ../../../mem/ruby/protocol/DMA_Controller.py ./
ln -s ../../../mem/ruby/protocol/Directory_Controller.py ./
ln -s ../../../mem/ruby/protocol/L1Cache_Controller.py ./
ln -s ../../../mem/ruby/protocol/L2Cache_Controller.py ./
ln -s ../../../mem/ruby/system/RubySystem.py ./
ln -s ../../../../../src/mem/ruby/system/Sequencer.py ./
ln -s ../../../../../src/mem/ruby/structures/RubyCache.py ./
ln -s ../../../../../src/mem/ruby/structures/DirectoryMemory.py ./
ln -s ../../../../../src/mem/ruby/structures/RubyPrefetcher.py ./
ln -s ../../../../../src/mem/ruby/structures/WireBuffer.py ./
ln -s ../../../../../src/mem/ruby/network/BasicLink.py ./
ln -s ../../../../../src/mem/ruby/network/BasicRouter.py ./
ln -s ../../../../../src/mem/ruby/network/MessageBuffer.py ./
ln -s ../../../../../src/mem/ruby/network/Network.py ./
ln -s ../../../../../src/mem/ruby/network/fault_model/FaultModel.py ./
ln -s ../../../../../src/mem/ruby/network/simple/SimpleLink.py ./
ln -s ../../../../../src/mem/ruby/network/simple/SimpleNetwork.py ./
ln -s ../../../../../src/mem/ruby/network/garnet/GarnetLink.py ./
ln -s ../../../../../src/mem/ruby/network/garnet/GarnetNetwork.py ./
ln -s ../../../../../src/mem/probes/BaseMemProbe.py ./
ln -s ../../../../../src/mem/probes/StackDistProbe.py ./
ln -s ../../../../../src/mem/probes/MemFootprintProbe.py ./
ln -s ../../../../../src/mem/probes/MemTraceProbe.py ./
ln -s ../../../../../src/mem/cache/Cache.py ./
ln -s ../../../../../src/mem/cache/tags/Tags.py ./
ln -s ../../../../../src/mem/cache/tags/indexing_policies/IndexingPolicies.py ./
ln -s ../../../../../src/mem/cache/prefetch/Prefetcher.py ./
ln -s ../../../../../src/mem/cache/compressors/Compressors.py ./
ln -s ../../../../../src/mem/cache/replacement_policies/ReplacementPolicies.py ./
ln -s ../../../../../src/mem/qos/QoSMemCtrl.py ./
ln -s ../../../../../src/mem/qos/QoSMemSinkCtrl.py ./
ln -s ../../../../../src/mem/qos/QoSMemSinkInterface.py ./
ln -s ../../../../../src/mem/qos/QoSPolicy.py ./
ln -s ../../../../../src/mem/qos/QoSTurnaround.py ./
ln -s ../../../../../src/sst/OutgoingRequestBridge.py ./
ln -s ../../../../../src/learning_gem5/part2/SimpleObject.py ./
ln -s ../../../../../src/learning_gem5/part2/HelloObject.py ./
ln -s ../../../../../src/learning_gem5/part2/SimpleMemobj.py ./
ln -s ../../../../../src/learning_gem5/part2/SimpleCache.py ./
ln -s ../../../../../src/base/Graphics.py ./
ln -s ../../../../../src/base/vnc/Vnc.py ./
ln -s ../../../../../src/base/filters/BloomFilters.py ./
ln -s ../../../../../src/dev/Device.py ./
ln -s ../../../../../src/dev/IntPin.py ./
ln -s ../../../../../src/dev/ResetPort.py ./
ln -s ../../../../../src/dev/Platform.py ./
ln -s ../../../../../src/dev/BadDevice.py ./
ln -s ../../../../../src/dev/net/Ethernet.py ./
ln -s ../../../../../src/dev/virtio/VirtIO.py ./
ln -s ../../../../../src/dev/virtio/VirtIOConsole.py ./
ln -s ../../../../../src/dev/virtio/VirtIOBlock.py ./
ln -s ../../../../../src/dev/virtio/VirtIORng.py ./
ln -s ../../../../../src/dev/virtio/VirtIO9P.py ./
ln -s ../../../../../src/dev/storage/Ide.py ./
ln -s ../../../../../src/dev/storage/DiskImage.py ./
ln -s ../../../../../src/dev/storage/SimpleDisk.py ./
ln -s ../../../../../src/dev/pci/PciDevice.py ./
ln -s ../../../../../src/dev/pci/PciHost.py ./
ln -s ../../../../../src/dev/pci/CopyEngine.py ./
ln -s ../../../../../src/dev/x86/Pc.py ./
ln -s ../../../../../src/dev/x86/SouthBridge.py ./
ln -s ../../../../../src/dev/x86/Cmos.py ./
ln -s ../../../../../src/dev/x86/I8259.py ./
ln -s ../../../../../src/dev/x86/I8254.py ./
ln -s ../../../../../src/dev/x86/I8237.py ./
ln -s ../../../../../src/dev/x86/I8042.py ./
ln -s ../../../../../src/dev/x86/X86Ide.py ./
ln -s ../../../../../src/dev/x86/PcSpeaker.py ./
ln -s ../../../../../src/dev/x86/I82094AA.py ./
ln -s ../../../../../src/dev/x86/X86QemuFwCfg.py ./
ln -s ../../../../../src/dev/serial/Serial.py ./
ln -s ../../../../../src/dev/serial/Terminal.py ./
ln -s ../../../../../src/dev/serial/Uart.py ./
ln -s ../../../../../src/dev/i2c/I2C.py ./
ln -s ../../../../../src/dev/qemu/QemuFwCfg.py ./
ln -s ../../../../../src/dev/ps2/PS2.py ./
ln -s ../../../../../src/python/m5/objects/__init__.py ./
ln -s ../../../../../src/python/m5/objects/SimObject.py ./
